baseurl = "https://fgeo.netlify.com/"
title = "fgeo blog"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "ForestGEO"
disqusShortname = "fgeo"
googleAnalytics = "UA-117163749-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]

[Author]
    name = "Mauro Lepore"
    profile = "https://forestgeo.github.io/fgeo/"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "fgeo blog"
    description = "A blog for those who use and build the fgeo package"
    github = "https://github.com/forestgeo/fgeo.blog"
#    gitlab = "https://gitlab.com/XXX"
#    linkedin = "https://linkedin.com/in/XXX/"
#    gplus = "https://google.com/+XXX"
    twitter = "https://twitter.com/mauro_lepore"
#    stackoverflow = "https://stackoverflow.com/users/XXX/YYY"
#    email = "maurolepore@gmail.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4
